# Generated by Django 4.2.6 on 2023-10-23 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "idCustomer",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="idCliente"
                    ),
                ),
                ("cName", models.CharField(max_length=100, verbose_name="Cliente")),
                ("cPhone", models.CharField(max_length=100, verbose_name="Telefone")),
                (
                    "cEmail",
                    models.CharField(max_length=100, null=True, verbose_name="E-mail"),
                ),
                (
                    "cVendedor",
                    models.CharField(max_length=100, verbose_name="Vendedor"),
                ),
                (
                    "cDescription",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "dContractCreated",
                    models.DateField(null=True, verbose_name="Contrato desde"),
                ),
                (
                    "nContractDuration",
                    models.IntegerField(null=True, verbose_name="Tempo de Contrato"),
                ),
                ("dCreated", models.DateTimeField(auto_now_add=True)),
                ("dLastUpdate", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesMan",
            fields=[
                ("idSalesMan", models.IntegerField(primary_key=True, serialize=False)),
                ("cName", models.CharField(max_length=100)),
                ("cPhone", models.CharField(max_length=100)),
                ("cEmail", models.CharField(max_length=100)),
                ("dCreated", models.DateTimeField(auto_now_add=True)),
                ("dLastUpdate", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("idContract", models.IntegerField(primary_key=True, serialize=False)),
                ("dStart", models.DateField()),
                ("cDescription", models.TextField(blank=True, null=True)),
                ("nDuration", models.IntegerField()),
                ("dCreated", models.DateTimeField(auto_now_add=True)),
                ("dLastUpdate", models.DateTimeField(null=True)),
                (
                    "idCustomer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="furukawa.customer",
                    ),
                ),
                (
                    "idSalesMan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="furukawa.salesman",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("idContact", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "cName",
                    models.CharField(max_length=100, verbose_name="Nome Contato"),
                ),
                ("cPhone", models.CharField(max_length=100, verbose_name="Telefone")),
                ("cEmail", models.CharField(max_length=100, verbose_name="Email")),
                ("dCreated", models.DateTimeField(auto_now_add=True)),
                ("dLastUpdate", models.DateTimeField(null=True)),
                (
                    "idCustomer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="furukawa.customer",
                    ),
                ),
            ],
        ),
    ]
